baseURL = 'https://crieaporradeum.blog/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'Crie a Porra de um Blog'
disableKinds = ['taxonomy', 'taxonomyTerm']

[menu]
  [[menu.main]]
        identifier = 'blog'
        name = '📝 Blog'
        url = '/posts/'
        weight = 2

  [[menu.main]]
        identifier = 'home'
        name = '🏠 Início'
        url = '/'
        weight = 1
